# Generated by Django 4.1.1 on 2022-09-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_checklistaction_service_checklistactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='retainerservice',
            name='checklistActions',
            field=models.ManyToManyField(related_name='retainerchecklistActions', to='api.checklistaction'),
        ),
    ]
