# Generated by Django 4.1.1 on 2022-09-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_retainerservice_checklistactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('billingAddress', models.TextField(blank=True, null=True)),
                ('emailAddress', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('billingInfo', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
