# Generated by Django 4.1.1 on 2022-09-27 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_aircrafttype_airport_fbo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tailNumber', models.CharField(max_length=50)),
                ('estimatedETA', models.DateTimeField()),
                ('estimatedETD', models.DateTimeField()),
                ('completeBy', models.DateTimeField()),
                ('status', models.CharField(choices=[('A', 'Accepted'), ('S', 'Assigned'), ('W', 'WIP'), ('C', 'Complete'), ('T', 'Cancelled'), ('R', 'Review'), ('I', 'Invoiced')], default='A', max_length=1)),
                ('aircraftType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.aircrafttype')),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.airport')),
                ('assignees', models.ManyToManyField(related_name='assignees', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.customer')),
                ('fbo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.fbo')),
                ('retainerServices', models.ManyToManyField(related_name='retainerservices', to='api.retainerservice')),
                ('services', models.ManyToManyField(related_name='services', to='api.service')),
            ],
        ),
    ]
