# Generated by Django 4.1.1 on 2022-09-27 21:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_jobcomments_date_jobcomments_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='requestDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
