# Generated by Django 4.1.1 on 2022-09-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_job_requestdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobphotos',
            name='photourl',
        ),
        migrations.AddField(
            model_name='jobphotos',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='jobphotos',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('A', 'Accepted'), ('S', 'Assigned'), ('U', 'Submitted'), ('W', 'WIP'), ('C', 'Complete'), ('T', 'Cancelled'), ('R', 'Review'), ('I', 'Invoiced')], default='A', max_length=1),
        ),
    ]
