# Generated by Django 4.1.1 on 2022-09-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_jobphotos_options_alter_job_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='completeBy',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='estimatedETA',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='estimatedETD',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='retainerServices',
            field=models.ManyToManyField(blank=True, related_name='retainerservices', to='api.retainerservice'),
        ),
        migrations.AlterField(
            model_name='job',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='services', to='api.service'),
        ),
    ]
