# Generated by Django 4.1.1 on 2022-09-29 20:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0016_alter_job_completeby_alter_job_estimatedeta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='assignees', to=settings.AUTH_USER_MODEL),
        ),
    ]
