# Generated by Django 4.1.1 on 2022-09-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_job_assignees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='completeBy',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='estimatedETA',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='estimatedETD',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
