# Generated by Django 4.1.1 on 2022-09-29 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_job_completeby_alter_job_estimatedeta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobphotos',
            name='interior',
            field=models.BooleanField(default=False),
        ),
    ]
