# Generated by Django 4.1.1 on 2022-10-01 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_jobphotos_interior'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobcomments',
            options={'verbose_name_plural': 'Job Comments'},
        ),
    ]
