# Generated by Django 4.1.1 on 2022-10-02 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_userprofile_email_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_spending_info', models.BooleanField(default=False)),
                ('allow_cancel_job', models.BooleanField(default=False)),
                ('retainer_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('show_job_price', models.BooleanField(default=False)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
            ],
            options={
                'verbose_name_plural': 'Customer Settings',
            },
        ),
    ]
