# Generated by Django 4.1.1 on 2022-10-02 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0026_customersettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('customer_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='api.customersettings')),
            ],
        ),
    ]
