# Generated by Django 4.1.1 on 2022-10-02 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0027_customeradmin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeradmin',
            options={'verbose_name_plural': 'Customer Admins'},
        ),
        migrations.CreateModel(
            name='CustomerProjectManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_managers', to='api.customersettings')),
                ('project_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Customer Project Managers',
            },
        ),
    ]
