# Generated by Django 4.1.1 on 2022-10-02 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_customeradmin_options_customerprojectmanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField()),
                ('type', models.CharField(choices=[('S', 'By Service'), ('A', 'By Airport'), ('G', 'General')], max_length=1)),
                ('customer_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='api.customersettings')),
            ],
        ),
    ]
