# Generated by Django 4.1.1 on 2022-10-02 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_customerdiscount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerdiscount',
            options={'verbose_name_plural': 'Customer Discounts'},
        ),
        migrations.CreateModel(
            name='CustomerDiscountService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.customerdiscount')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.service')),
            ],
        ),
    ]
