# Generated by Django 4.1.1 on 2022-10-02 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_customerdiscountservice_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAdditionalFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('type', models.CharField(choices=[('F', 'By FBO'), ('A', 'By Airport')], max_length=1)),
                ('customer_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='api.customersettings')),
            ],
            options={
                'verbose_name_plural': 'Customer Additional Fees',
            },
        ),
        migrations.CreateModel(
            name='CustomerAdditionalFeeFBO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_additional_feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fbos', to='api.customeradditionalfee')),
                ('fbo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fbo')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAdditionalFeeAirport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.airport')),
                ('customer_additional_feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airports', to='api.customeradditionalfee')),
            ],
        ),
    ]
