# Generated by Django 4.1.1 on 2022-10-02 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_customeradditionalfee_customeradditionalfeefbo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeradditionalfeefbo',
            old_name='customer_additional_feed',
            new_name='customer_additional_fee',
        ),
    ]
