# Generated by Django 4.1.1 on 2022-10-02 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_rename_customer_additional_feed_customeradditionalfeefbo_customer_additional_fee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeradditionalfeefbo',
            options={'verbose_name_plural': 'Customer Additional Fee FBOs'},
        ),
        migrations.RenameField(
            model_name='customeradditionalfeeairport',
            old_name='customer_additional_feed',
            new_name='customer_additional_fee',
        ),
    ]
