# Generated by Django 4.1.1 on 2022-10-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_customeradditionalfeeairport_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerretainerservice',
            options={'verbose_name_plural': 'Customer Retainer Services'},
        ),
        migrations.AddField(
            model_name='customerretainerservice',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
