# Generated by Django 4.1.1 on 2022-10-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_userprofile_allow_set_as_busy'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='actual_completion_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='estimated_completion_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
