# Generated by Django 4.1.1 on 2022-10-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_job_actual_completion_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='purchase_order',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
