# Generated by Django 4.1.1 on 2022-10-03 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_job_purchase_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimatedServiceTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_time', models.PositiveIntegerField()),
                ('aircraft_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aircrafttype')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimated_service_times', to='api.service')),
            ],
            options={
                'verbose_name_plural': 'Estimated Service Times',
            },
        ),
    ]
