# Generated by Django 4.1.1 on 2022-10-03 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0041_estimatedservicetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatedservicetime',
            name='estimated_time',
            field=models.PositiveIntegerField(verbose_name='Estimated Time (minutes)'),
        ),
        migrations.AlterField(
            model_name='job',
            name='actual_completion_time',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Actual Completion Time (minutes)'),
        ),
        migrations.AlterField(
            model_name='job',
            name='estimated_completion_time',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Estimated Completion Time (minutes)'),
        ),
        migrations.CreateModel(
            name='JobStatusActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Accepted'), ('S', 'Assigned'), ('U', 'Submitted'), ('W', 'WIP'), ('C', 'Complete'), ('T', 'Cancelled'), ('R', 'Review'), ('I', 'Invoiced')], max_length=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_activities', to='api.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
