# Generated by Django 4.1.1 on 2022-10-04 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_jobserviceassignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobserviceassignment',
            options={'verbose_name_plural': 'Job Service Assignments'},
        ),
        migrations.AlterModelTable(
            name='jobserviceassignment',
            table='api_job_service_assignment',
        ),
    ]
