# Generated by Django 4.1.1 on 2022-10-04 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0045_alter_jobserviceassignment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRetainerServiceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Assigned'), ('W', 'WIP'), ('C', 'Completed')], default='A', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_retainer_service_assignments', to='api.job')),
                ('project_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('retainer_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.retainerservice')),
            ],
            options={
                'verbose_name_plural': 'Job Retainer Service Assignments',
            },
        ),
    ]
