# Generated by Django 4.1.1 on 2022-10-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_alter_customersettings_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='retainerServices',
            field=models.ManyToManyField(blank=True, related_name='retainer_services', to='api.retainerservice'),
        ),
    ]
