# Generated by Django 4.1.1 on 2022-10-07 18:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_alter_service_checklistactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobphotos',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
