# Generated by Django 4.1.1 on 2022-10-07 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0053_jobphotos_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobphotos',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_photos', to=settings.AUTH_USER_MODEL),
        ),
    ]
