# Generated by Django 4.1.1 on 2022-10-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_jobphotos_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobphotos',
            name='size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
