# Generated by Django 4.1.1 on 2022-10-14 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_job_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_list', to='api.job')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.service')),
            ],
            options={
                'db_table': 'api.job_services',
            },
        ),
    ]
