# Generated by Django 4.1.1 on 2022-10-14 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_jobservices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobservices',
            old_name='job',
            new_name='job_id',
        ),
        migrations.RenameField(
            model_name='jobservices',
            old_name='service',
            new_name='service_id',
        ),
    ]
