# Generated by Django 4.1.1 on 2022-10-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_alter_jobretainerserviceassignment_project_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobphotos',
            name='customer_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
