# Generated by Django 4.1.1 on 2022-10-17 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_jobcommentcheck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='retainerServices',
        ),
        migrations.RemoveField(
            model_name='job',
            name='services',
        ),
    ]
