# Generated by Django 4.1.1 on 2022-10-17 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_remove_job_retainerservices_remove_job_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='assignees',
        ),
    ]
