# Generated by Django 4.1.1 on 2022-10-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_customersettings_price_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
