# Generated by Django 4.1.1 on 2022-10-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_job_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeradditionalfee',
            name='percentage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerdiscount',
            name='percentage',
            field=models.BooleanField(default=False),
        ),
    ]
