# Generated by Django 4.1.1 on 2022-10-21 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0070_alter_customer_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='banner',
            field=models.ImageField(blank=True, upload_to='customers/'),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL),
        ),
    ]
