# Generated by Django 4.1.1 on 2022-10-24 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_userprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersettings',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_settings', to='api.customer'),
        ),
    ]
