# Generated by Django 4.1.1 on 2022-10-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_alter_customersettings_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='emailAddress',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customeradditionalfee',
            name='type',
            field=models.CharField(choices=[('F', 'By FBO'), ('A', 'By Airport'), ('G', 'General')], max_length=1),
        ),
    ]
