# Generated by Django 4.1.1 on 2022-10-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_job_is_auto_priced'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='on_site',
            field=models.BooleanField(default=False),
        ),
    ]
