# Generated by Django 4.1.1 on 2022-11-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_job_completion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobstatusactivity',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='jobstatusactivity',
            name='status',
            field=models.CharField(choices=[('A', 'Accepted'), ('S', 'Assigned'), ('U', 'Submitted'), ('W', 'WIP'), ('C', 'Complete'), ('T', 'Cancelled'), ('R', 'Review'), ('I', 'Invoiced'), ('P', 'Price Changed')], max_length=1),
        ),
    ]
