# Generated by Django 4.1.1 on 2022-11-08 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_alter_pricelist_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='TailAircraftLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tail_number', models.CharField(max_length=255, unique=True)),
                ('aircraft_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tail_aircraft_lookup', to='api.aircrafttype')),
            ],
            options={
                'ordering': ['tail_number'],
            },
        ),
    ]
