# Generated by Django 4.1.1 on 2022-11-08 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_tailaircraftlookup'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailaircraftlookup',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tail_aircraft_lookup', to='api.customer'),
        ),
    ]
