# Generated by Django 4.1.1 on 2022-11-08 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_alter_tailaircraftlookup_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TailServiceLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tail_number', models.CharField(max_length=255, unique=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tail_service_lookup', to='api.service')),
            ],
            options={
                'ordering': ['tail_number'],
            },
        ),
    ]
