# Generated by Django 4.1.1 on 2022-11-08 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_tailservicelookup'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailservicelookup',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tail_service_lookup', to='api.customer'),
            preserve_default=False,
        ),
    ]
