# Generated by Django 4.1.1 on 2022-11-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_tailservicelookup_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tailservicelookup',
            name='tail_number',
            field=models.CharField(max_length=255),
        ),
    ]
