# Generated by Django 4.1.1 on 2022-11-16 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_alter_tailservicelookup_tail_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TailRetainerServiceLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tail_number', models.CharField(max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tail_retainer_service_lookup', to='api.customer')),
                ('retainer_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tail_retainer_service_lookup', to='api.retainerservice')),
            ],
            options={
                'ordering': ['tail_number'],
            },
        ),
    ]
