# Generated by Django 4.1.1 on 2022-11-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_alter_tailaircraftlookup_tail_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcomments',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
