# Generated by Django 4.1.1 on 2022-11-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_jobcomments_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersettings',
            name='retainer_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
