# Generated by Django 4.1.1 on 2022-11-21 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0091_alter_customersettings_retainer_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected')], default='P', max_length=1)),
                ('is_processed', models.BooleanField(default=False)),
                ('tailNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('aircraftType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.aircrafttype')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_estimates', to='api.customer')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_estimates', to='api.job')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_estimates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobServiceEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('job_estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_service_estimates', to='api.jobestimate')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.service')),
            ],
            options={
                'verbose_name_plural': 'Job Service Estimates',
            },
        ),
    ]
