# Generated by Django 4.1.1 on 2022-11-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_jobestimate_jobserviceestimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobestimate',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
