# Generated by Django 4.1.1 on 2022-11-22 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_jobestimatediscount_jobestimateadditionalfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobestimate',
            name='fbo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.fbo'),
        ),
    ]
