# Generated by Django 4.1.1 on 2022-11-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_jobestimate_fbo'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
