# Generated by Django 4.1.1 on 2022-11-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_servicetype_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobestimate',
            old_name='price',
            new_name='total_price',
        ),
        migrations.AddField(
            model_name='jobestimate',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='jobestimate',
            name='services_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
