# Generated by Django 4.1.1 on 2022-11-24 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_rename_price_jobestimate_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fbo',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
