# Generated by Django 4.1.1 on 2022-11-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_userprofile_sms_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobstatusactivity',
            name='activity_type',
            field=models.CharField(choices=[('E', 'Departure Changed'), ('A', 'Arrival Changed'), ('B', 'Complete Before Changed'), ('P', 'Price Changed'), ('O', 'Airport Changed'), ('F', 'FBO Changed'), ('S', 'Status Changed'), ('T', 'Tail Number Changed'), ('U', 'Photos Uploaded')], default='S', max_length=1),
        ),
    ]
