# Generated by Django 4.1.1 on 2022-12-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_jobstatusactivity_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobretainerserviceassignment',
            name='status',
            field=models.CharField(choices=[('U', 'Unassigned'), ('A', 'Assigned'), ('W', 'WIP'), ('C', 'Completed')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='jobstatusactivity',
            name='status',
            field=models.CharField(choices=[('A', 'Accepted'), ('S', 'Assigned'), ('U', 'Submitted'), ('W', 'WIP'), ('C', 'Complete'), ('T', 'Cancelled'), ('R', 'Review'), ('I', 'Invoiced'), ('P', 'Price Changed'), ('X', 'Project Manager Unassigned')], max_length=1),
        ),
    ]
