# Generated by Django 4.1.1 on 2022-12-02 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0104_alter_jobretainerserviceassignment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Assigned'), ('W', 'WIP'), ('C', 'Complete')], default='A', max_length=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_activities', to='api.job')),
                ('project_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_activities', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='api.service')),
            ],
        ),
        migrations.CreateModel(
            name='RetainerServiceActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Assigned'), ('W', 'WIP'), ('C', 'Complete')], default='A', max_length=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retainer_service_activities', to='api.job')),
                ('project_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retainer_service_activities', to=settings.AUTH_USER_MODEL)),
                ('retainer_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='api.retainerservice')),
            ],
        ),
    ]
