# Generated by Django 4.1.1 on 2022-12-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_serviceactivity_retainerserviceactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retainerserviceactivity',
            name='status',
            field=models.CharField(choices=[('W', 'WIP'), ('C', 'Complete')], max_length=1),
        ),
        migrations.AlterField(
            model_name='serviceactivity',
            name='status',
            field=models.CharField(choices=[('W', 'WIP'), ('C', 'Complete')], max_length=1),
        ),
    ]
