# Generated by Django 4.1.1 on 2022-12-04 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0106_alter_retainerserviceactivity_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='api.airport'),
        ),
    ]
