# Generated by Django 4.1.1 on 2022-12-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_alter_job_airport'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='requested_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
