# Generated by Django 4.1.1 on 2022-12-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_job_requested_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='customer_purchase_order',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
