# Generated by Django 4.1.1 on 2022-12-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0110_userprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='enable_estimates',
            field=models.BooleanField(default=False),
        ),
    ]
