# Generated by Django 4.1.1 on 2022-12-15 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0111_userprofile_enable_estimates'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAvailableAirport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='available_users', to='api.airport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='available_airports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
