# Generated by Django 4.1.1 on 2022-12-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0112_useravailableairport'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='enable_invoice',
            field=models.BooleanField(default=False),
        ),
    ]
