# Generated by Django 4.1.1 on 2022-12-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0115_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('bg-red-400', 'red'), ('bg-orange-400', 'orange'), ('bg-amber-400', 'amber'), ('bg-yellow-400', 'yellow'), ('bg-lime-400', 'lime'), ('bg-green-400', 'green'), ('bg-indigo-400', 'indigo'), ('bg-violet-400', 'violet'), ('bg-purple-400', 'purple'), ('bg-fuchsia-400', 'fuchsia'), ('bg-pink-400', 'pink'), ('bg-rose-400', 'rose')], default='bg-red-400', max_length=255),
        ),
    ]
