# Generated by Django 4.1.1 on 2023-02-04 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0118_tailalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('I', 'Interior'), ('E', 'Exterior'), ('O', 'Other')], default='O', max_length=1),
        ),
    ]
