# Generated by Django 4.1.1 on 2023-02-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0120_retainerservice_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobestimate',
            name='show_totals',
            field=models.BooleanField(default=True),
        ),
    ]
