# Generated by Django 4.1.1 on 2023-03-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0122_tag_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('red', 'red'), ('orange', 'orange'), ('amber', 'amber'), ('slate', 'slate'), ('lime', 'lime'), ('emerald', 'emerald'), ('cyan', 'cyan'), ('blue', 'blue'), ('indigo', 'indigo'), ('violet', 'violet'), ('fuchsia', 'fuchsia'), ('pink', 'pink')], default='red', max_length=255),
        ),
    ]
