# Generated by Django 4.1.1 on 2023-05-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0126_alter_customeradditionalfee_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobstatusactivity',
            name='activity_type',
            field=models.CharField(choices=[('E', 'Departure Changed'), ('A', 'Arrival Changed'), ('B', 'Complete Before Changed'), ('P', 'Price Changed'), ('O', 'Airport Changed'), ('F', 'FBO Changed'), ('S', 'Status Changed'), ('T', 'Tail Number Changed'), ('U', 'Photos Uploaded'), ('R', 'Job Returned')], default='S', max_length=1),
        ),
    ]
