# Generated by Django 4.1.1 on 2023-06-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0127_alter_jobstatusactivity_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='show_job_price',
            field=models.BooleanField(default=False),
        ),
    ]
