# Generated by Django 4.1.1 on 2023-06-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0128_userprofile_show_job_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceactivity',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
