# Generated by Django 4.1.1 on 2023-07-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0129_serviceactivity_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='prompt_requested_by',
            field=models.BooleanField(default=False, help_text='For customers users that use generic profiles, this will prompt them to enter their name when creating a job.'),
        ),
    ]
