# Generated by Django 4.1.1 on 2023-08-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0130_userprofile_prompt_requested_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='inventory_email_notifications',
            field=models.BooleanField(default=True, help_text='Only applicable to admins and account managers'),
        ),
    ]
