# Generated by Django 4.1.1 on 2023-09-14 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0131_userprofile_inventory_email_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirportAvailableFbo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='available_fbos', to='api.airport')),
                ('fbo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='available_airports', to='api.fbo')),
            ],
        ),
    ]
