# Generated by Django 4.1.1 on 2023-11-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0137_alter_jobfiles_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobfiles',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
