# Generated by Django 4.1.1 on 2023-11-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0138_jobfiles_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailalert',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tailalert',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
