# Generated by Django 4.1.1 on 2023-11-21 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0139_tailalert_comment_alter_tailalert_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tailalert',
            old_name='comment',
            new_name='notes',
        ),
    ]
