# Generated by Django 4.1.1 on 2023-11-27 12:31

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0140_rename_comment_tailalert_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TailFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='file')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('size', models.PositiveIntegerField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('tail_alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.tailalert')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tail_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tail Files',
            },
        ),
    ]
