# Generated by Django 4.1.1 on 2023-12-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0142_usercustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='hours_worked',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='minutes_worked',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='number_of_workers',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
