# Generated by Django 4.1.1 on 2024-01-10 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0144_job_labor_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tailNumber', models.CharField(max_length=50)),
                ('is_recurrent', models.BooleanField(default=False)),
                ('repeat_every', models.PositiveIntegerField(blank=True, null=True)),
                ('aircraftType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.aircrafttype')),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='api.airport')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='api.customer')),
                ('fbo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.fbo')),
            ],
        ),
    ]
