# Generated by Django 4.1.1 on 2024-01-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0145_jobschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobschedule',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Used for non-recurrent schedules', null=True),
        ),
        migrations.AlterField(
            model_name='jobschedule',
            name='repeat_every',
            field=models.PositiveIntegerField(blank=True, help_text='Used for recurrent schedules', null=True),
        ),
    ]
