# Generated by Django 4.1.1 on 2024-01-11 19:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0147_jobschedule_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
