# Generated by Django 4.1.1 on 2024-01-12 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0148_jobschedule_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobScheduleService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_schedule_services', to='api.jobschedule')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.service')),
            ],
            options={
                'verbose_name_plural': 'Job Schedule Services',
            },
        ),
        migrations.CreateModel(
            name='JobScheduleRetainerService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_schedule_retainer_services', to='api.jobschedule')),
                ('retainer_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.retainerservice')),
            ],
            options={
                'verbose_name_plural': 'Job Schedule Retainer Services',
            },
        ),
    ]
