# Generated by Django 4.1.1 on 2024-01-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0149_jobscheduleservice_jobscheduleretainerservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobschedule',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
