# Generated by Django 4.1.1 on 2024-01-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0151_job_job_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobschedule',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
