# Generated by Django 4.1.1 on 2024-02-22 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0153_jobscheduletag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerretainerservice',
            name='count',
        ),
        migrations.RemoveField(
            model_name='customerretainerservice',
            name='customer_setting',
        ),
        migrations.AddField(
            model_name='customerretainerservice',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='retainer_services', to='api.customer'),
            preserve_default=False,
        ),
    ]
