# Generated by Django 4.1.1 on 2024-03-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0155_customerservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_external',
            field=models.BooleanField(default=True),
        ),
    ]
