# Generated by Django 4.1.1 on 2024-03-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0157_job_additional_cost_job_subcontractor_profit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='additional_cost',
            new_name='interval_additional_cost',
        ),
        migrations.AddField(
            model_name='job',
            name='vendor_additional_cost',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
