# Generated by Django 4.1.1 on 2024-03-11 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0159_jobretainerserviceassignment_vendor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='api.vendor'),
        ),
    ]
