# Generated by Django 4.1.1 on 2024-03-12 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0160_alter_job_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='interval_additional_cost',
            new_name='internal_additional_cost',
        ),
    ]
