# Generated by Django 4.1.1 on 2024-03-19 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0161_rename_interval_additional_cost_job_internal_additional_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='show_all_services_report',
            field=models.BooleanField(default=False, help_text='If enabled, the external project manager will see all services completed by its vendor in the service report. If disabled, the external project manager will only see what its been completed by him/her'),
        ),
    ]
