# Generated by Django 4.1.1 on 2024-04-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0163_userprofile_show_airport_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='enable_confirm_jobs',
            field=models.BooleanField(default=False, help_text='If enabled, the user will be able to confirm jobs. If disabled, the user will not be able to confirm jobs. Admins can always confirm jobs.'),
        ),
    ]
