# Generated by Django 4.1.1 on 2024-04-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0164_userprofile_enable_confirm_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='confirmed_email',
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='confirmed_full_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='confirmed_phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_publicly_confirmed',
            field=models.BooleanField(default=False, help_text='It is set to true when the job is confirmed via a public link.'),
        ),
    ]
