# Generated by Django 4.1.1 on 2024-04-09 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0165_job_confirmed_email_job_confirmed_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobstatusactivity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='status_activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
