# Generated by Django 4.1.1 on 2024-04-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0166_alter_jobstatusactivity_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeradditionalfee',
            name='type',
            field=models.CharField(choices=[('F', 'By FBO'), ('A', 'By Airport'), ('G', 'General'), ('V', 'Vendor')], max_length=1),
        ),
    ]
