# Generated by Django 4.1.1 on 2024-04-11 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0167_alter_customeradditionalfee_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAdditionalFeeVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.airport')),
                ('customer_additional_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='api.customeradditionalfee')),
            ],
            options={
                'verbose_name_plural': 'Customer Additional Fee Vendors',
            },
        ),
    ]
