# Generated by Django 4.1.1 on 2024-04-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0169_alter_customeradditionalfee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeradditionalfee',
            name='type',
            field=models.CharField(choices=[('F', 'FBO Fee'), ('A', 'Travel Fees'), ('G', 'General'), ('V', 'Higher Vendor Price'), ('M', 'Management Fees')], max_length=1),
        ),
    ]
