# Generated by Django 4.1.1 on 2024-04-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0171_job_fbo_fees_amount_applied_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobestimateadditionalfee',
            name='type',
            field=models.CharField(choices=[('F', 'FBO Fee'), ('A', 'Travel Fees'), ('G', 'General'), ('V', 'Vendor Price Difference'), ('M', 'Management Fees')], max_length=1),
        ),
    ]
