# Generated by Django 4.1.1 on 2024-04-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0172_alter_jobestimateadditionalfee_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='enable_accept_jobs',
            field=models.BooleanField(default=False, help_text='If enabled, the user will be able to accept jobs. This is only applicable to project managers. If disabled, the project manager will skip the acceptance process and go straigh to start job.'),
        ),
    ]
