# Generated by Django 4.1.1 on 2024-04-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0175_job_returned_email_job_returned_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='arrival_formatted_date',
            field=models.CharField(blank=True, help_text='This is the formatted date for the arrival date and time of the job to avoid complications with timezones when sending emails and sms notifications', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='complete_before_formatted_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='departure_formatted_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
