# Generated by Django 4.1.1 on 2024-04-24 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0176_job_arrival_formatted_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='arrival_formatted_date',
            field=models.CharField(blank=True, help_text='This is the formatted date for the arrival date and time of the job to avoid complications with timezones when sending emails and sms notifica', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='LastProjectManagersNotified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_managers_notified', to='api.job')),
                ('project_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_managers_notified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
