# Generated by Django 4.1.1 on 2024-04-25 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0177_alter_job_arrival_formatted_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAcceptanceNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acceptance_notifications', to='api.job')),
                ('project_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acceptance_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
