# Generated by Django 4.1.1 on 2024-04-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0178_jobacceptancenotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='enable_all_airports',
            field=models.BooleanField(default=False, help_text='If enabled, the user will be able to see all airports in the system. If disabled, the user will only see the airports that are associated with the user.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='enable_all_customers',
            field=models.BooleanField(default=False, help_text='If enabled, the user will be able to see all customers in the system. If disabled, the user will only see the customers that are associated with the user.'),
        ),
    ]
