# Generated by Django 4.1.1 on 2024-05-04 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0180_userprofile_enable_email_notification_inventory_out_of_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='enable_sms_notification_job_accepted',
        ),
    ]
