# Generated by Django 4.1.1 on 2024-05-04 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0182_remove_userprofile_enable_sms_notification_job_comment_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='enable_email_notification_job_assigned',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='enable_sms_notification_job_assigned',
        ),
    ]
