# Generated by Django 4.1.1 on 2024-05-04 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0185_remove_userprofile_enable_sms_notification_scheduled_job_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='enable_sms_notification_inventory_out_of_stock',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='enable_sms_notification_inventory_threshold_met',
        ),
    ]
