# Generated by Django 4.1.1 on 2024-05-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0188_userprofile_enable_sms_notification_job_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('A', 'Accepted'), ('S', 'Assigned'), ('U', 'Submitted'), ('W', 'WIP'), ('C', 'Complete'), ('T', 'Cancelled'), ('R', 'Review'), ('I', 'Invoiced'), ('N', 'Not Invoiced')], default='A', max_length=1),
        ),
    ]
