# Generated by Django 4.1.1 on 2024-05-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0191_customersettings_enable_approval_process_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersettings',
            name='enable_request_priority',
            field=models.BooleanField(default=False, help_text='If enabled, the customer will be able to request priority service when creating a job'),
        ),
    ]
