# Generated by Django 4.1.1 on 2024-07-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0192_customersettings_enable_request_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='enable_inventory_dashboard',
            field=models.BooleanField(default=False, help_text='If enabled, the user will be able to see the inventory dashboard. Applicable to Internal Coordinators. Admins can always see the inventory dashboard.'),
        ),
    ]
