# Generated by Django 4.1.1 on 2024-07-12 12:18

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0193_userprofile_enable_inventory_dashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('file', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='file')),
                ('photo', models.ImageField(blank=True, upload_to='help/')),
                ('url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_level', models.CharField(choices=[('A', 'All'), ('C', 'Customer'), ('E', 'External Project Manager'), ('P', 'Internal Project Manager'), ('I', 'Internal Coordinator'), ('D', 'Admin')], default='A', max_length=1)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='help_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
