# Generated by Django 4.1.1 on 2024-07-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0194_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='file_type',
            field=models.CharField(choices=[('F', 'File'), ('P', 'Photo'), ('U', 'URL')], default='F', max_length=1),
        ),
    ]
