# Generated by Django 4.1.1 on 2024-07-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0195_help_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
