# Generated by Django 4.1.1 on 2024-07-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0197_fbo_hours_of_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobestimate',
            name='accepted_email',
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
        migrations.AddField(
            model_name='jobestimate',
            name='accepted_full_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='jobestimate',
            name='accepted_phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
