# Generated by Django 4.1.1 on 2024-08-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0199_airport_airport_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='fbo',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
