# Generated by Django 4.1.1 on 2024-09-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0201_airport_fee_percentage_fbo_fee_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='show_all_services_report',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='master_vendor_pm',
            field=models.BooleanField(default=False, help_text='If enabled, the external project manager will see all services completed by its vendor in the service report. If disabled, the external project manager will only see what its been completed by him/her. Additionally, the master vendor PM can see all jobs assigned to any PM in the vendor, and it can re-assign jobs to any PM in the vendor.'),
        ),
    ]
