# Generated by Django 4.1.1 on 2024-09-10 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0204_invoicedservice_invoicedfee_invoiceddiscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='invoiced_price_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='api.pricelist'),
        ),
    ]
