# Generated by Django 4.1.1 on 2024-09-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0205_alter_job_invoiced_price_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
