# Generated by Django 4.1.1 on 2024-09-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0206_job_discounted_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
