# Generated by Django 4.1.1 on 2024-09-17 11:02

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0207_alter_job_discounted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='billing_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='emails',
            field=models.CharField(blank=True, help_text='Comma separated list of emails', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='logo',
            field=models.ImageField(blank=True, upload_to='vendors/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='phone_numbers',
            field=models.CharField(blank=True, help_text='Comma separated list of phone numbers', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='VendorFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='file')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('size', models.PositiveIntegerField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_files', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.vendor')),
            ],
            options={
                'verbose_name_plural': 'Vendor Files',
            },
        ),
    ]
