# Generated by Django 4.1.1 on 2024-09-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0208_vendor_billing_address_vendor_emails_vendor_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
