# Generated by Django 4.1.1 on 2024-11-11 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0209_vendor_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='is_vendor',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='VendorCustomerPriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_customer_price_lists', to='api.customer')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_customer_price_lists', to='api.pricelist')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_customer_price_lists', to='api.vendor')),
            ],
        ),
    ]
