# Generated by Django 4.1.1 on 2024-12-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0210_pricelist_is_vendor_vendorcustomerpricelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorfile',
            name='expiration_date',
            field=models.DateField(blank=True, help_text='Applicable for insurance files', null=True),
        ),
        migrations.AddField(
            model_name='vendorfile',
            name='file_type',
            field=models.CharField(blank=True, choices=[('I', 'Insurance'), ('W', 'W-9'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='vendorfile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorfile',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
