# Generated by Django 4.1.1 on 2025-01-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0213_jobfolloweremail_customerfolloweremail'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='enable_flightaware_tracking',
            field=models.BooleanField(default=False),
        ),
    ]
