# Generated by Django 4.1.1 on 2025-01-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0214_job_enable_flightaware_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='TailIdent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tail_number', models.CharField(max_length=255, unique=True)),
                ('ident', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
