# Generated by Django 4.1.1 on 2025-03-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0216_retainerservice_is_special_service_is_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobfiles',
            name='is_customer_only',
            field=models.BooleanField(default=False),
        ),
    ]
