# Generated by Django 4.1.1 on 2025-05-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0219_jobstatusactivity_service_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='exterior_service_checker',
            field=models.PositiveIntegerField(default=0, help_text='Refers to the number of arrived flights to be checked before suggesting an exterior service level 2', verbose_name='Exterior Service Checker'),
        ),
    ]
