# Generated by Django 4.1.1 on 2025-05-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0220_customer_exterior_service_checker'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_exterior_detail_level_2',
            field=models.BooleanField(default=False, help_text='This service is used to suggest an exterior service level 2 when the number of arrived flights exceeds the exterior service checker value in the customer settings.', verbose_name='Exterior Detail Level 2'),
        ),
    ]
