# Generated by Django 4.1.1 on 2025-06-19 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0221_service_is_exterior_detail_level_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tail_number', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('has_flight_activity', models.BooleanField(default=True, help_text='Indicates if the tail has any flight activity associated with it for the last 10 days')),
                ('aircraft_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tails', to='api.aircrafttype')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tails', to='api.customer')),
            ],
        ),
    ]
