# Generated by Django 4.1.1 on 2025-06-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0222_customertail'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_exterior_detail_level_1',
            field=models.BooleanField(default=False, verbose_name='Exterior Detail Level 1'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_interior_detail_level_1',
            field=models.BooleanField(default=False, verbose_name='Interior Detail Level 1'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_interior_detail_level_2',
            field=models.BooleanField(default=False, verbose_name='Interior Detail Level 2'),
        ),
    ]
