# Generated by Django 4.1.1 on 2025-06-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0223_service_is_exterior_detail_level_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersettings',
            name='enable_flight_based_scheduled_cleaning',
            field=models.BooleanField(default=False, help_text='If enabled, a daily job will be run to check which tail numbers require cleaning based on the number of flights completed since last service. Admins will receive an email notification with the list of tails that require cleaning.'),
        ),
    ]
