# Generated by Django 4.1.1 on 2025-06-19 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0224_customersettings_enable_flight_based_scheduled_cleaning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customertail',
            name='aircraft_type',
        ),
    ]
