# Generated by Django 4.1.1 on 2025-06-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0225_remove_customertail_aircraft_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertail',
            name='aircraft_type_name',
            field=models.CharField(blank=True, help_text='Name of the aircraft type associated with this tail number', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customertail',
            name='flights_since_last_exterior_level_1_service',
            field=models.IntegerField(default=0, help_text='Number of flights since the last exterior level 1 service'),
        ),
        migrations.AddField(
            model_name='customertail',
            name='flights_since_last_exterior_level_2_service',
            field=models.IntegerField(default=0, help_text='Number of flights since the last exterior level 2 service'),
        ),
        migrations.AddField(
            model_name='customertail',
            name='flights_since_last_interior_level_1_service',
            field=models.IntegerField(default=0, help_text='Number of flights since the last interior level 1 service'),
        ),
        migrations.AddField(
            model_name='customertail',
            name='flights_since_last_interior_level_2_service',
            field=models.IntegerField(default=0, help_text='Number of flights since the last interior level 2 service'),
        ),
        migrations.AddField(
            model_name='customertail',
            name='is_exterior_level_1_service_due',
            field=models.BooleanField(default=False, help_text='Indicates if the exterior level 1 service is due'),
        ),
        migrations.AddField(
            model_name='customertail',
            name='is_exterior_level_2_service_due',
            field=models.BooleanField(default=False, help_text='Indicates if the exterior level 2 service is due'),
        ),
        migrations.AddField(
            model_name='customertail',
            name='is_interior_level_1_service_due',
            field=models.BooleanField(default=False, help_text='Indicates if the interior level 1 service is due'),
        ),
        migrations.AddField(
            model_name='customertail',
            name='is_interior_level_2_service_due',
            field=models.BooleanField(default=False, help_text='Indicates if the interior level 2 service is due'),
        ),
        migrations.AddField(
            model_name='customertail',
            name='last_exterior_level_1_location',
            field=models.CharField(blank=True, help_text='Airport initials for last known location for exterior level 1 service', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='customertail',
            name='last_exterior_level_1_service_date',
            field=models.DateTimeField(blank=True, help_text='Date of the last exterior level 1 service', null=True),
        ),
        migrations.AddField(
            model_name='customertail',
            name='last_exterior_level_2_location',
            field=models.CharField(blank=True, help_text='Airport initials for last known location for exterior level 2 service', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='customertail',
            name='last_exterior_level_2_service_date',
            field=models.DateTimeField(blank=True, help_text='Date of the last exterior level 2 service', null=True),
        ),
        migrations.AddField(
            model_name='customertail',
            name='last_interior_level_1_location',
            field=models.CharField(blank=True, help_text='Airport initials for last known location for interior level 1 service', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='customertail',
            name='last_interior_level_1_service_date',
            field=models.DateTimeField(blank=True, help_text='Date of the last interior level 1 service', null=True),
        ),
        migrations.AddField(
            model_name='customertail',
            name='last_interior_level_2_location',
            field=models.CharField(blank=True, help_text='Airport initials for last known location for interior level 2 service', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='customertail',
            name='last_interior_level_2_service_date',
            field=models.DateTimeField(blank=True, help_text='Date of the last interior level 2 service', null=True),
        ),
        migrations.AddField(
            model_name='customertail',
            name='status',
            field=models.CharField(choices=[('O', 'OK'), ('I', 'In Maintenance'), ('N', 'No Flight History'), ('S', 'Service Due')], default='O', help_text='Current status of the tail', max_length=1),
        ),
    ]
