# Generated by Django 4.1.1 on 2025-06-25 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0226_customertail_aircraft_type_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customertail',
            name='has_flight_activity',
        ),
    ]
