# Generated by Django 4.1.1 on 2025-07-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0227_remove_customertail_has_flight_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertail',
            name='is_viewed',
            field=models.BooleanField(default=False, help_text='Indicates if the tail has been viewed by the a user. Set manually by the user.'),
        ),
    ]
