# Generated by Django 4.1.1 on 2025-07-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0228_customertail_is_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertail',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp of the last update to this tail'),
        ),
    ]
