# Generated by Django 4.1.1 on 2025-07-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0229_customertail_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertail',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
