# Generated by Django 4.1.1 on 2025-07-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0230_customertail_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_job_submitter_only',
            field=models.BooleanField(default=False, help_text='If enabled, the user will only be able to submit jobs. This is meant for users that only submnit jobs. We only show functionality related to job submission, and hide all other functionality.'),
        ),
    ]
