# Generated by Django 4.1.1 on 2025-07-20 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0231_userprofile_is_job_submitter_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='retainerservice',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='retainerservice',
            name='short_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='short_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
