# Generated by Django 4.1.1 on 2025-07-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0232_retainerservice_short_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='expo_push_token',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
