# Generated by Django 4.1.1 on 2025-08-19 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0234_exportjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportjob',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to='api.customer'),
        ),
    ]
