# Generated by Django 4.1.1 on 2025-08-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0235_exportjob_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportjob',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
