# Generated by Django 4.1.1 on 2025-08-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0236_exportjob_notified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportjob',
            name='task_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
