# Generated by Django 4.1.1 on 2025-09-15 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0237_exportjob_task_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='feedback_rating',
            field=models.PositiveIntegerField(blank=True, help_text='Rating from 1 to 5 given by the customer once the job is completed', null=True),
        ),
        migrations.CreateModel(
            name='JobFeedbackPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('job_feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.jobfeedback')),
            ],
        ),
        migrations.AddField(
            model_name='jobfeedback',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='api.job'),
        ),
    ]
