# Generated by Django 4.1.1 on 2025-09-15 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0238_jobfeedback_job_feedback_rating_jobfeedbackphotos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='feedback_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks_given', to=settings.AUTH_USER_MODEL),
        ),
    ]
