# Generated by Django 4.1.1 on 2025-09-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0239_job_feedback_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersettings',
            name='hide_addons_services',
            field=models.BooleanField(default=False, help_text='If enabled, all users flagged as Submitters Only that belong to this customer will not see addons services when creating a job.'),
        ),
    ]
