# Generated by Django 4.1.1 on 2025-10-24 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0241_customercategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_categories', to=settings.AUTH_USER_MODEL)),
                ('customer_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_categories', to='api.customercategory')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='api.job')),
            ],
            options={
                'verbose_name_plural': 'Job Categories',
            },
        ),
    ]
