from .jobs import JobListView
from .users import UserView
from .job_detail import JobDetail
from .job_service_assignment import (
    JobServiceAssignmentView
    )
from .job_retainer_service_assignment import JobRetainerServiceAssignmentView
from .job_photos import JobPhotosView
from .job_photos_upload import JobPhotosUploadView
from .user_avatar import UserAvatarView
from .user_reset_password import UserResetPasswordView
from .job_comment import JobCommentView
from .job_stats import JobStatsView
from .job_form_info import JobFormInfoView
from .create_job import CreateJobView
from .edit_job import EditJobView
from .services import ServicesView
from .job_detail_basic import JobDetailBasicView
from .customers import CustomersView
from .customer_detail import CustomerDetail
from .customer_settings import CustomerSettingsView
from .customer_discounts import CustomerDiscountView
from .airports import AirportsView
from .customer_discount_update import CustomerDiscountUpdateView
from .customer_fees import CustomerFeesView
from .fbos import FBOsView
from .customer_fee_update import CustomerFeeUpdateView
from .price_list import PriceListView
from .customer_users import CustomerUsersView
from .create_customer import CreateCustomerView
from .retainer_services import RetainerServicesView