# Generated by Django 4.1.1 on 2023-08-04 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('measure_by', models.CharField(choices=[('U', 'Unit'), ('G', 'Gallons'), ('B', 'Bottle'), ('O', 'Box'), ('L', 'Lb'), ('J', 'Jar'), ('T', 'Other')], default='U', max_length=1)),
                ('area', models.CharField(choices=[('I', 'Interior'), ('E', 'Exterior'), ('B', 'Interior and Exterior'), ('O', 'Office')], default='I', max_length=1)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=9)),
                ('photo', models.ImageField(blank=True, upload_to='images/')),
                ('active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.brand')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('minimum_required', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('C', 'Confirmed'), ('U', 'Unconfirmed')], default='U', help_text='User will have the option to change to confirmed while in the Checking Inventory View.                                        When an Item gets adjusted by either adding or subtracting, the status will change to unconfirmed.', max_length=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_items', to='inventory.item')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_items', to='inventory.location')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(choices=[('red', 'red'), ('orange', 'orange'), ('amber', 'amber'), ('slate', 'slate'), ('lime', 'lime'), ('emerald', 'emerald'), ('cyan', 'cyan'), ('blue', 'blue'), ('indigo', 'indigo'), ('violet', 'violet'), ('fuchsia', 'fuchsia'), ('pink', 'pink')], default='red', max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LocationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_user', to='inventory.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LocationItemActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('A', 'Add'), ('M', 'Move'), ('S', 'Subtract')], max_length=1)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Summation of price per unit and quantity', max_digits=10, null=True)),
                ('location_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='inventory.locationitem')),
                ('moved_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moved_from', to='inventory.location')),
                ('moved_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moved_to', to='inventory.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tags', to='inventory.item')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_tags', to='inventory.tag')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.provider'),
        ),
    ]
