# Generated by Django 4.1.1 on 2023-08-04 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_brand_active_location_active_provider_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='provider',
        ),
        migrations.CreateModel(
            name='ItemProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='providers', to='inventory.item')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_providers', to='inventory.provider')),
            ],
        ),
    ]
