# Generated by Django 4.1.4 on 2023-08-11 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_item_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationitem',
            name='minimum_required',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='locationitem',
            name='threshold',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
