# Generated by Django 4.1.4 on 2023-08-12 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_locationitembrand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationitem',
            name='brand',
        ),
    ]
