# Generated by Django 4.1.4 on 2023-08-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_locationitem_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationitemactivity',
            name='activity_type',
            field=models.CharField(choices=[('A', 'Add'), ('M', 'Move'), ('S', 'Subtract'), ('C', 'Confirm')], max_length=1),
        ),
    ]
