# Generated by Django 4.1.4 on 2023-08-13 21:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_locationitemactivity_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationitemactivity',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
