# Generated by Django 4.1.4 on 2023-08-24 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0012_locationitemactivity_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='measure_by',
            field=models.CharField(choices=[('U', 'Unit'), ('G', 'Gallons'), ('B', 'Bottle/Sprayer'), ('O', 'Box'), ('L', 'Lb'), ('J', 'Jar'), ('T', 'Other')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='locationuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
