# Generated by Django 4.1.1 on 2023-08-28 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_item_measure_by_alter_locationuser_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyGeneralStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('total_items', models.IntegerField()),
                ('total_quantity', models.IntegerField()),
                ('total_cost', models.DecimalField(decimal_places=2, help_text='This refers to the total cost of all items in the inventory. Each item quantity multiply by the cost per unit.', max_digits=9)),
                ('total_moves', models.IntegerField()),
                ('total_additions', models.IntegerField()),
                ('total_add_cost', models.DecimalField(decimal_places=2, max_digits=9)),
                ('total_subtractions', models.IntegerField()),
                ('total_expense', models.DecimalField(decimal_places=2, help_text='This refers to the total cost of all items that were subtracted from the inventory.', max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='DailyLocationStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('total_items', models.IntegerField()),
                ('total_quantity', models.IntegerField()),
                ('total_cost', models.DecimalField(decimal_places=2, help_text='This refers to the total cost of all items in the inventory. Each item quantity multiply by the cost per unit.', max_digits=9)),
                ('total_moves', models.IntegerField()),
                ('total_additions', models.IntegerField()),
                ('total_add_cost', models.DecimalField(decimal_places=2, max_digits=9)),
                ('total_subtractions', models.IntegerField()),
                ('total_expense', models.DecimalField(decimal_places=2, help_text='This refers to the total cost of all items that were subtracted from the inventory.', max_digits=9)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='inventory.location')),
            ],
        ),
    ]
