# Generated by Django 4.1.1 on 2023-08-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_remove_dailygeneralstats_total_moves_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStatsAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateField()),
            ],
        ),
    ]
