# Generated by Django 4.1.1 on 2023-09-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_dailystatsaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationitem',
            name='on_hold',
            field=models.BooleanField(default=False),
        ),
    ]
