# Generated by Django 4.1.1 on 2023-09-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_locationitem_on_hold'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='enable_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
