from django.urls import path
from .views import (
        JobListView,
        UserView,
        JobDetail,
        JobServiceAssignmentView,
        JobRetainerServiceAssignmentView,
        JobPhotosView,
        JobPhotosUploadView,
        UserAvatarView,
        UserResetPasswordView,
        JobCommentView,
        JobStatsView,
        JobFormInfoView,
        CreateJobView,
        EditJobView,
        ServicesView,
        JobDetailBasicView,
        CustomersView,
        CustomerDetail,
        CustomerSettingsView,
        CustomerDiscountView,
        AirportsView,
        CustomerDiscountUpdateView,
        CustomerFeesView,
        FBOsView,
        CustomerFeeUpdateView,
        PriceListView,
        CustomerUsersView,
        CreateCustomerView,
        RetainerServicesView,
        CompletedJobsListView,
        JobCloseoutView,
        JobExportCSVView
    )

urlpatterns = [
    path('jobs', JobListView.as_view()),
    path('jobs/form-info', JobFormInfoView.as_view()),
    path('jobs/create', CreateJobView.as_view()),
    path('jobs/export', JobExportCSVView.as_view()),
    path('jobs/completed', CompletedJobsListView.as_view()),
    path('jobs/completed/<int:id>/', CompletedJobsListView.as_view()),
    path('jobs/closeout/<int:id>/', JobCloseoutView.as_view()),
    path('jobs/<int:id>/', JobDetail.as_view()),
    path('jobs/basic/<int:id>/', JobDetailBasicView.as_view()),
    path('jobs/edit/<int:id>/', EditJobView.as_view()),
    path('jobs/stats/<int:id>/', JobStatsView.as_view()),
    path('jobs/services/<int:id>/', JobServiceAssignmentView.as_view()),
    path('jobs/retainer-services/<int:id>/', JobRetainerServiceAssignmentView.as_view()),
    path('job-photos/<int:jobid>/', JobPhotosView.as_view()),
    path('job-photos/delete/<int:jobid>/', JobPhotosView.as_view()),
    path('job-photos/upload/<int:jobid>/', JobPhotosUploadView.as_view()),
    path('job-comments/<int:jobid>/', JobCommentView.as_view()),
    path('services', ServicesView.as_view()),
    path('retainer-services', RetainerServicesView.as_view()),
    path('airports', AirportsView.as_view()),
    path('fbos', FBOsView.as_view()),
    path('price-list', PriceListView.as_view()),
    path('customers', CustomersView.as_view()),
    path('customers/create', CreateCustomerView.as_view()),
    path('customers/users', CustomerUsersView.as_view()),
    path('customers/<int:id>/', CustomerDetail.as_view()),
    path('customers/settings/<int:id>/', CustomerSettingsView.as_view()),
    path('customers/discounts/<int:id>/', CustomerDiscountView.as_view()),
    path('customers/discounts/update/<int:id>/', CustomerDiscountUpdateView.as_view()),
    path('customers/fees/<int:id>/', CustomerFeesView.as_view()),
    path('customers/fees/update/<int:id>/', CustomerFeeUpdateView.as_view()),
    path('users/me', UserView.as_view()),
    path('users/me/avatar', UserAvatarView.as_view()),
    path('users/me/reset-password', UserResetPasswordView.as_view())
]